### ISSUE TITLE
"Take photo" crashes

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#258]
There's a toast message that says "Could not open uri" and then this stacktrace:

```
08-11 07:40:39.379 19482 19482 E ACRA    : ACRA caught a RuntimeException for net.cyclestreets
08-11 07:40:39.379 19482 19482 E ACRA    : java.lang.RuntimeException: Unable to resume activity {net.cyclestreets/net.cyclestreets.CycleStreets}: java.lang.RuntimeException: You must pass an IMyLocationProvider to setMyLocationProvider()
08-11 07:40:39.379 19482 19482 E ACRA    :     	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3124)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3155)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at android.os.Handler.dispatchMessage(Handler.java:102)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at android.os.Looper.loop(Looper.java:148)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at android.app.ActivityThread.main(ActivityThread.java:5459)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at java.lang.reflect.Method.invoke(Native Method)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
08-11 07:40:39.379 19482 19482 E ACRA    : Caused by: java.lang.RuntimeException: You must pass an IMyLocationProvider to setMyLocationProvider()
08-11 07:40:39.379 19482 19482 E ACRA    :     	at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.setMyLocationProvider(MyLocationNewOverlay.java:197)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.enableMyLocation(MyLocationNewOverlay.java:535)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.enableMyLocation(MyLocationNewOverlay.java:564)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at net.cyclestreets.views.overlay.LocationOverlay.enableLocation(LocationOverlay.java:65)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at net.cyclestreets.views.CycleMapView.onResume(CycleMapView.java:156)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at net.cyclestreets.PhotoUploadFragment.setupMap(PhotoUploadFragment.java:522)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at net.cyclestreets.PhotoUploadFragment.setupView(PhotoUploadFragment.java:411)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at net.cyclestreets.PhotoUploadFragment.onResume(PhotoUploadFragment.java:284)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at android.app.Fragment.performResume(Fragment.java:2263)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1008)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1130)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1965)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at android.app.FragmentController.dispatchResume(FragmentController.java:174)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at android.app.Activity.performResume(Activity.java:6356)
08-11 07:40:39.379 19482 19482 E ACRA    :     	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3113)
```

@mvl22, are you able to check whether this bug exists on the last non-beta release?  I've never really used this feature, and I also can't remember it ever not crashing when I explored the app.
That way we can tell if this is a regression or just a longstanding bug, which will affect whether we try to fix it in time for #255.

**Comment by jf1** [comment]
I don't get a crash or error message on v3.7/1476 (using 'Take a photo' in 'Add photo' when not logged in and with geolocation disabled).

**Comment by oliverlockwood** [comment]
@jf1 interesting. What version of Android are you running? And, if you have the time, would you mind experimenting with the same operation if logged in and/or with location enabled?

**Comment by jf1** [comment]
It's a Samsung S5 running 6.0.1
No crash when I logged in mid-process, or when repeating it while logged in throughout.
Location was on but unused the first time. I got CS to acquire location before the second run, but its interest is in the photo's geolocation (which was never present) rather than the device's.

ps. Perhaps alert users to the need to register and log in at an earlier stage in this process?

**Comment by oliverlockwood** [comment]
Thanks very much for the feedback. From a bit of digging it seems that, depending on the camera implementation (which may vary e.g. in Samsung-flavoured Android) then our code may or may not work. I am preparing a fix at the moment which, according to the official Android documentation, should be universally suitable.

Very good point about asking for permissions earlier in the process. Thanks for the suggestion, I'll incorporate it in the upcoming fix, and perhaps you can verify once we have a beta build out.

**Comment by oliverlockwood** [comment]
The latest beta build (version name: `3.6`, code: `1483`) solves the problems that I had identified in this issue.

@jf1 would you mind please:
1.  verifying that these changes haven't impacted your ability to upload images, whether taken in the app or selected from previous photos?

2.  giving feedback on the new journey behaviour (in terms of asking people to register/login earlier in the process) which I changed at your suggestion?
