### ISSUE TITLE
App crashes every startup if minimised when on map settings page and no offline maps available

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#263]
### 1.  Navigate to this screen:

<img width="300" alt="screen shot 2018-08-15 at 12 16 35" src="https://user-images.githubusercontent.com/6017680/44145998-938c9396-a085-11e8-8a47-a8967155d2ee.png">

### 2. Minimise/maximise the app.
It crashes.

It then crashes every time you try to start the app up again.  Here's the stacktrace:
```
08-15 12:17:47.300 1156-1156/net.cyclestreets E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.cyclestreets, PID: 1156
    java.lang.RuntimeException: Unable to resume activity {net.cyclestreets/net.cyclestreets.CycleStreets}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.View.getContext()' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3645)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3685)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2898)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.View.getContext()' on a null object reference
        at net.cyclestreets.util.MessageBox.YesNo(MessageBox.java:16)
        at net.cyclestreets.SettingsFragment.setMapFileSummary(SettingsFragment.java:151)
        at net.cyclestreets.SettingsFragment.setSummary(SettingsFragment.java:135)
        at net.cyclestreets.SettingsFragment.onCreate(SettingsFragment.java:36)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2331)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1386)
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1188)
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1071)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2380)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:382)
        at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:488)
        at net.cyclestreets.MainNavDrawerActivity.onResume(MainNavDrawerActivity.java:172)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1354)
        at android.app.Activity.performResume(Activity.java:7079)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3620)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3685) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2898) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by oliverlockwood** [comment]
Fix successfully verified on my phone through the beta update.  I've escaped the infinite crash trap 😆
