### ISSUE TITLE
NPE: fatal crash in some circumstances when pressing Back

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#368]
Note that this is unrelated to #364 (or the fix for it).

This has been seen as a crash scenario in the Play console & I've figured out how to reproduce it myself.

Use the Nav menu to go:
- Add Photo
- Settings
- Add Photo
Then press Back a couple of times, it crashes.

Stack trace is:
```
2020-04-25 18:43:37.686 13847-13847/net.cyclestreets E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.cyclestreets, PID: 13847
    kotlin.KotlinNullPointerException
        at net.cyclestreets.addphoto.AddPhotoFragment.prefs(AddPhotoFragment.kt:424)
        at net.cyclestreets.addphoto.AddPhotoFragment.store(AddPhotoFragment.kt:366)
        at net.cyclestreets.addphoto.AddPhotoFragment.onBackPressed(AddPhotoFragment.kt:570)
        at net.cyclestreets.MainNavDrawerActivity.onBackPressed(MainNavDrawerActivity.kt:180)
        at android.app.Activity.onKeyUp(Activity.java:3641)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2825)
        at android.app.Activity.dispatchKeyEvent(Activity.java:3958)
        at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:367)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5413)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5281)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4947)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5004)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4980)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5141)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3064)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2607)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2598)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3041)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

Looks like in certain pathways the Fragment's Activity is null.

**Comment by jezhiggins** [comment]
Good catch. I'll pick this up tomorrow. On 25 Apr 2020 18:48, Oliver Lockwood <notifications@github.com> wrote:
Note that this is unrelated to #364 (or the fix for it).
This has been seen as a crash scenario in the Play console & I've figured out how to reproduce it myself.
Use the Nav menu to go:
Add PhotoSettingsAdd Photo
Then press Back a couple of times, it crashes.
Stack trace is:
2020-04-25 18:43:37.686 13847-13847/net.cyclestreets E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.cyclestreets, PID: 13847
    kotlin.KotlinNullPointerException
        at net.cyclestreets.addphoto.AddPhotoFragment.prefs(AddPhotoFragment.kt:424)
        at net.cyclestreets.addphoto.AddPhotoFragment.store(AddPhotoFragment.kt:366)
        at net.cyclestreets.addphoto.AddPhotoFragment.onBackPressed(AddPhotoFragment.kt:570)
        at net.cyclestreets.MainNavDrawerActivity.onBackPressed(MainNavDrawerActivity.kt:180)
        at android.app.Activity.onKeyUp(Activity.java:3641)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2825)
        at android.app.Activity.dispatchKeyEvent(Activity.java:3958)
        at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:367)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5413)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5281)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4947)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5004)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4980)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5141)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3064)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2607)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2598)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3041)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

Looks like in certain pathways the Fragment's Activity is null.

**Comment by jezhiggins** [comment]
I've found the immediate problem - MainNavDrawerActivity.currentFragment gets out of date and consequently we call a method on a fragment which isn't visible. I think there's a wider problem in the back button handling - we've (well, I :smiley:) interfere with the back button handling, so I want to have a better look at that and see if it's sustainable.

**Comment by oliverlockwood** [comment]
Oh, and further context that springs to mind: when I first got involved with the app, pressing Back in pretty much any context caused the app to minimise, which I found really frustrating and unintuitive and so at some point I changed it :-)

**Comment by jezhiggins** [comment]
This commit fixes the NPE https://github.com/cyclestreets/android/commit/41980c393379185f5e5ec4e0eb7edae318fd6b77

I wonder if it makes sense to try and preserve Back button behaviour through navigation drawer choices. For example, the Twitter app doesn't. If you choose something from the nav drawer, it launches a new activity so you can only go back to the main activity. If you choose a different fragment using the tabs along the bottom, pressing back takes you to the main timeline fragment. After that, you leave the app.  Gmail is similar. You can choose as many different things - folders or lables - from the navigation drawer, but pressing back does one of two things. You go back to the main activity, or you leave the app. 

I wonder if we should simplify. What do you think about this? 
* if you're on the journey planner, back leaves the app
* if you're not on the journey planner, back should take you to the journey planner
* unless you're part way through adding a photo, in which case back takes you to the previous step
* or you're on a setting subscreen, in which case back return you to settings

**Comment by oliverlockwood** [comment]
The above is _more or less_ what I was trying to achieve when I brought in the `backOutableFragments` bit; hence the comment I had put in the code explaining the idea:

>```
>// The Journey Planner and Photomap are the 'heart' of the app.  Pressing 'back' on any other
>// fragment should eventually return you to whichever of those you were using.
>```

The only difference from what I had in mind, versus your description above, is that I had considered the Photomap an alternative place to go "back" to.  Particularly from the context of adding a photo it seemed to make more intuitive sense than returning to the Journey planner.

However personally I don't ever use the Photomap so I'd be perfectly happy to go with the model you propose above; feel free to rip out and rework as much as you like, I'm not in the least bit precious about the implementation I had put in.

**Comment by jezhiggins** [comment]
I shall have a go 🙂On 26 Apr 2020 16:40, Oliver Lockwood <notifications@github.com> wrote:
The above is more or less what I was trying to achieve when I brought in the backOutableFragments bit; hence the comment I had put in the code explaining the idea:

// The Journey Planner and Photomap are the 'heart' of the app.  Pressing 'back' on any other
// fragment should eventually return you to whichever of those you were using.


The only difference from what I had in mind, versus your description above, is that I had considered the Photomap an alternative place to go "back" to.  Particularly from the context of adding a photo it seemed to make more intuitive sense than returning to the Journey planner.
However personally I don't ever use the Photomap so I'd be perfectly happy to go with the model you propose above; feel free to rip out and rework as much as you like, I'm not in the least bit precious about the implementation I had put in.

**Comment by mvl22** [comment]
> The Journey Planner and Photomap are the 'heart' of the app.

Yes, +1 on this. They are essentially the dual ‘homes’ of the app, and the back behaviour should try to work on that basis.
