### ISSUE TITLE
Upgrade OSMdroid and mapsforge

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#446]
I kept the version bumps of these out of #444, based on past experience.  To little surprise, a patch version bump of osmdroid contains breaking changes 🙄 

When I started up with:
```gradle
  mapsforgeVersion = '0.14.0'
  osmdroidVersion = '6.1.8'
```
(instead of 0.13.0 and 6.1.6) I saw the following:

```
2020-10-05 08:51:11.573 25185-25185/net.cyclestreets D/MainNavDrawerActivity: Loading page with menuItemId=2131362028 (Journey planner)
2020-10-05 08:51:11.588 25185-25185/net.cyclestreets D/util.Permissions: Permission android.permission.WRITE_EXTERNAL_STORAGE has already been granted
2020-10-05 08:51:11.588 25185-25185/net.cyclestreets V/CycleMapFragment: Already have android.permission.WRITE_EXTERNAL_STORAGE permission
2020-10-05 08:51:11.610 25185-25185/net.cyclestreets I/StorageUtils: /storage/emulated/0 is NOT writable
2020-10-05 08:51:11.611 25185-25185/net.cyclestreets D/StorageUtils: /proc/mounts
2020-10-05 08:51:11.612 25185-25185/net.cyclestreets D/StorageUtils: /dev/block/dm-2 / ext4 ro,seclabel,nodev,relatime,block_validity,delalloc,barrier,user_xattr 0 0
2020-10-05 08:51:11.612 25185-25185/net.cyclestreets D/StorageUtils: tmpfs /dev tmpfs rw,seclabel,nosuid,relatime,mode=755 0 0
2020-10-05 08:51:11.612 25185-25185/net.cyclestreets D/StorageUtils: devpts /dev/pts devpts rw,seclabel,relatime,mode=600,ptmxmode=000 0 0
2020-10-05 08:51:11.612 25185-25185/net.cyclestreets D/StorageUtils: none /dev/cg2_bpf cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
2020-10-05 08:51:11.612 25185-25185/net.cyclestreets D/StorageUtils: none /dev/cpuctl cgroup rw,nosuid,nodev,noexec,relatime,cpu 0 0
2020-10-05 08:51:11.612 25185-25185/net.cyclestreets D/StorageUtils: none /dev/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,noprefix,release_agent=/sbin/cpuset_release_agent 0 0
2020-10-05 08:51:11.612 25185-25185/net.cyclestreets D/StorageUtils: none /dev/memcg cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
2020-10-05 08:51:11.613 25185-25185/net.cyclestreets D/StorageUtils: none /dev/stune cgroup rw,nosuid,nodev,noexec,relatime,schedtune 0 0
2020-10-05 08:51:11.613 25185-25185/net.cyclestreets D/StorageUtils: adb /dev/usb-ffs/adb functionfs rw,relatime 0 0
2020-10-05 08:51:11.613 25185-25185/net.cyclestreets D/StorageUtils: proc /proc proc rw,relatime,gid=3009,hidepid=2 0 0
2020-10-05 08:51:11.613 25185-25185/net.cyclestreets D/StorageUtils: sysfs /sys sysfs rw,seclabel,relatime 0 0
2020-10-05 08:51:11.613 25185-25185/net.cyclestreets D/StorageUtils: selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
2020-10-05 08:51:11.613 25185-25185/net.cyclestreets D/StorageUtils: debugfs /sys/kernel/debug debugfs rw,seclabel,relatime,mode=755 0 0
2020-10-05 08:51:11.613 25185-25185/net.cyclestreets D/StorageUtils: tracefs /sys/kernel/debug/tracing tracefs rw,seclabel,relatime 0 0
2020-10-05 08:51:11.613 25185-25185/net.cyclestreets D/StorageUtils: bpf /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime 0 0
2020-10-05 08:51:11.613 25185-25185/net.cyclestreets D/StorageUtils: pstore /sys/fs/pstore pstore rw,seclabel,nosuid,nodev,noexec,relatime 0 0
2020-10-05 08:51:11.613 25185-25185/net.cyclestreets D/StorageUtils: tmpfs /mnt tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,mode=755,gid=1000 0 0
2020-10-05 08:51:11.613 25185-25185/net.cyclestreets D/StorageUtils: /data/media /mnt/runtime/default/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal 0 0
2020-10-05 08:51:11.613 25185-25185/net.cyclestreets D/StorageUtils: /data/media /mnt/runtime/read/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=23,derive_gid,default_normal 0 0
2020-10-05 08:51:11.613 25185-25185/net.cyclestreets D/StorageUtils: /data/media /mnt/runtime/write/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal 0 0
2020-10-05 08:51:11.614 25185-25185/net.cyclestreets D/StorageUtils: /data/media /mnt/runtime/full/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal 0 0
2020-10-05 08:51:11.614 25185-25185/net.cyclestreets D/StorageUtils: /dev/block/vold/public:253,80 /mnt/media_rw/19F4-1613 vfat rw,dirsync,nosuid,nodev,noexec,noatime,uid=1023,gid=1023,fmask=0007,dmask=0007,allow_utime=0020,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro 0 0
2020-10-05 08:51:11.614 25185-25185/net.cyclestreets D/StorageUtils: /mnt/media_rw/19F4-1613 /mnt/runtime/default/19F4-1613 sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,mask=6 0 0
2020-10-05 08:51:11.614 25185-25185/net.cyclestreets D/StorageUtils: /mnt/media_rw/19F4-1613 /mnt/runtime/read/19F4-1613 sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=18 0 0
2020-10-05 08:51:11.614 25185-25185/net.cyclestreets D/StorageUtils: /mnt/media_rw/19F4-1613 /mnt/runtime/write/19F4-1613 sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=18 0 0
2020-10-05 08:51:11.614 25185-25185/net.cyclestreets D/StorageUtils: /mnt/media_rw/19F4-1613 /mnt/runtime/full/19F4-1613 sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=7 0 0
2020-10-05 08:51:11.614 25185-25185/net.cyclestreets D/StorageUtils: tmpfs /apex tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,mode=755 0 0
2020-10-05 08:51:11.614 25185-25185/net.cyclestreets D/StorageUtils: /dev/block/dm-2 /apex/com.android.tzdata@290000000 ext4 ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr 0 0
2020-10-05 08:51:11.615 25185-25185/net.cyclestreets D/StorageUtils: /dev/block/dm-2 /apex/com.android.tzdata ext4 ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr 0 0
2020-10-05 08:51:11.615 25185-25185/net.cyclestreets D/StorageUtils: /dev/block/dm-2 /apex/com.android.runtime@1 ext4 ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr 0 0
2020-10-05 08:51:11.615 25185-25185/net.cyclestreets D/StorageUtils: /dev/block/dm-2 /apex/com.android.runtime ext4 ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr 0 0
2020-10-05 08:51:11.615 25185-25185/net.cyclestreets D/StorageUtils: /dev/block/dm-2 /apex/com.android.conscrypt@290000000 ext4 ro,seclabel,nodev,relatime,block_validity,delalloc,barrier,user_xattr 0 0
2020-10-05 08:51:11.615 25185-25185/net.cyclestreets D/StorageUtils: /dev/block/dm-2 /apex/com.android.conscrypt ext4 ro,seclabel,nodev,relatime,block_validity,delalloc,barrier,user_xattr 0 0
2020-10-05 08:51:11.615 25185-25185/net.cyclestreets D/StorageUtils: /dev/block/dm-2 /apex/com.android.media@290000000 ext4 ro,seclabel,nodev,relatime,block_validity,delalloc,barrier,user_xattr 0 0
2020-10-05 08:51:11.615 25185-25185/net.cyclestreets D/StorageUtils: /dev/block/dm-2 /apex/com.android.media ext4 ro,seclabel,nodev,relatime,block_validity,delalloc,barrier,user_xattr 0 0
2020-10-05 08:51:11.615 25185-25185/net.cyclestreets D/StorageUtils: /dev/block/dm-2 /apex/com.android.media.swcodec@290000000 ext4 ro,seclabel,nodev,relatime,block_validity,delalloc,barrier,user_xattr 0 0
2020-10-05 08:51:11.615 25185-25185/net.cyclestreets D/StorageUtils: /dev/block/dm-2 /apex/com.android.media.swcodec ext4 ro,seclabel,nodev,relatime,block_validity,delalloc,barrier,user_xattr 0 0
2020-10-05 08:51:11.615 25185-25185/net.cyclestreets D/StorageUtils: /dev/block/dm-2 /apex/com.android.resolv@290000000 ext4 ro,seclabel,nodev,relatime,block_validity,delalloc,barrier,user_xattr 0 0
2020-10-05 08:51:11.615 25185-25185/net.cyclestreets D/StorageUtils: /dev/block/dm-2 /apex/com.android.resolv ext4 ro,seclabel,nodev,relatime,block_validity,delalloc,barrier,user_xattr 0 0
2020-10-05 08:51:11.615 25185-25185/net.cyclestreets D/StorageUtils: /dev/block/dm-1 /vendor ext4 ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr 0 0
2020-10-05 08:51:11.615 25185-25185/net.cyclestreets D/StorageUtils: none /acct cgroup rw,nosuid,nodev,noexec,relatime,cpuacct 0 0
2020-10-05 08:51:11.615 25185-25185/net.cyclestreets D/StorageUtils: none /config configfs rw,nosuid,nodev,noexec,relatime 0 0
2020-10-05 08:51:11.615 25185-25185/net.cyclestreets D/StorageUtils: /dev/block/vdc /data ext4 rw,seclabel,nosuid,nodev,noatime,resgid=1065,errors=panic,data=ordered 0 0
2020-10-05 08:51:11.616 25185-25185/net.cyclestreets D/StorageUtils: nsfs /data/vendor/var/run/netns/router nsfs rw 0 0
2020-10-05 08:51:11.616 25185-25185/net.cyclestreets D/StorageUtils: tmpfs /storage tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,mode=755,gid=1000 0 0
2020-10-05 08:51:11.616 25185-25185/net.cyclestreets D/StorageUtils: /data/media /storage/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal 0 0
2020-10-05 08:51:11.616 25185-25185/net.cyclestreets D/StorageUtils: /mnt/media_rw/19F4-1613 /storage/19F4-1613 sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,mask=6 0 0
2020-10-05 08:51:11.616 25185-25185/net.cyclestreets D/StorageUtils: tmpfs /storage/self tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,mode=755,gid=1000 0 0
2020-10-05 08:51:11.616 25185-25185/net.cyclestreets I/StorageUtils: /sdcard is NOT writable
2020-10-05 08:51:11.629 25185-25185/net.cyclestreets I/StorageUtils: /storage/emulated/0 is NOT writable
2020-10-05 08:51:11.651 25185-25185/net.cyclestreets D/OsmDroid: Unable to create base path at null
    java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.osmdroid.tileprovider.util.StorageUtils$StorageInfo.path' on a null object reference
        at org.osmdroid.config.DefaultConfigurationProvider.getOsmdroidBasePath(DefaultConfigurationProvider.java:255)
        at org.osmdroid.config.DefaultConfigurationProvider.getOsmdroidBasePath(DefaultConfigurationProvider.java:247)
        at org.osmdroid.config.DefaultConfigurationProvider.load(DefaultConfigurationProvider.java:337)
        at net.cyclestreets.views.CycleMapView.<init>(CycleMapView.java:78)
        at net.cyclestreets.CycleMapFragment.onCreateView(CycleMapFragment.kt:53)
        at net.cyclestreets.RouteMapFragment.onCreateView(RouteMapFragment.kt:37)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:447)
        at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:458)
        at net.cyclestreets.MainNavDrawerActivity.onResume(MainNavDrawerActivity.kt:190)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1446)
        at android.app.Activity.performResume(Activity.java:7939)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-10-05 08:51:11.652 25185-25185/net.cyclestreets D/AndroidRuntime: Shutting down VM
2020-10-05 08:51:11.654 25185-25185/net.cyclestreets E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.cyclestreets, PID: 25185
    java.lang.RuntimeException: Unable to resume activity {net.cyclestreets/net.cyclestreets.CycleStreets}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
        at org.osmdroid.config.DefaultConfigurationProvider.load(DefaultConfigurationProvider.java:337)
        at net.cyclestreets.views.CycleMapView.<init>(CycleMapView.java:78)
        at net.cyclestreets.CycleMapFragment.onCreateView(CycleMapFragment.kt:53)
        at net.cyclestreets.RouteMapFragment.onCreateView(RouteMapFragment.kt:37)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:447)
        at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:458)
        at net.cyclestreets.MainNavDrawerActivity.onResume(MainNavDrawerActivity.kt:190)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1446)
        at android.app.Activity.performResume(Activity.java:7939)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
```

I'll look into this and resolve it separately.

**Comment by jezhiggins** [comment]
Now this does feel like the restricted app storage problem.

**Comment by oliverlockwood** [comment]
Righto.  I'll leave this one as-is to let you progress the offline map stuff first.
